/**
 * historyFrenchLexicon.js
 * Grand dictionnaire de référence Histoire-Géographie-EMC et vocabulaire général français.
 * Utilisé comme base de distracteurs pour que l'autocomplétion des jeux (Zombie & Starship)
 * corrige l'orthographe SANS dévoiler la réponse dès la première lettre.
 */

export const HISTOIRE_GEO_LEXICON = [
  // Antiquité grecque & romaine
  "Acropole", "Agora", "Alcibiade", "Alexandre le Grand", "Allégorie", "Amphithéâtre", "Amphore",
  "Anarchie", "Ancien Régime", "Antiquité", "Apollon", "Aqueduc", "Archonte", "Aréopage",
  "Aristocrate", "Aristocratie", "Aristote", "Artémis", "Athéna", "Athènes", "Athénien",
  "Banquet", "Barbare", "Bataille", "Basileus", "Bataille de Marathon", "Bataille de Salamine",
  "Boulè", "Bouleute", "Bronze", "Bureaucratie",
  "Campagne", "Capitole", "Capitulaire", "Carthage", "Catacombes", "Censure", "Céramique",
  "César", "Centurion", "Centurie", "Chariot", "Chronologie", "Cicéron", "Cimon",
  "Circonscription", "Cirque", "Cité", "Cité-État", "Citoyen", "Citoyenneté", "Civilisation",
  "Clisthène", "Cohorte", "Colonie", "Colisée", "Comices", "Commerce", "Consul", "Corinthe",
  "Cosmopolite", "Culte", "Culte impérial", "Culte civique", "Cynisme",
  "Dèce", "Délos", "Dème", "Déméter", "Demi-dieu", "Démocratie", "Démographie", "Démosthène",
  "Dictateur", "Dictature", "Dinar", "Diocèse", "Dioclétien", "Dionysos", "Disciple",
  "Dolmen", "Domaine", "Domination", "Draconien", "Droit", "Droits civiques", "Dynastie",
  "Ecclésia", "Édit de Milan", "Égalité", "Électeur", "Empire", "Empire romain", "Éphèbe",
  "Éphébie", "Épicurisme", "Épigraphie", "Esclave", "Esclavage", "Exil", "Expansion",
  "Forum", "Fresque", "Fronde",
  "Gaulois", "Gladiateur", "Gouverneur", "Grèce", "Guerre médique", "Guerre du Péloponnèse",
  "Hadrien", "Harpenteur", "Hégémonie", "Hélène", "Héliée", "Hellène", "Hellénistique",
  "Héphaïstos", "Héra", "Héraclès", "Héréditaire", "Hérésie", "Hérétique", "Hermès",
  "Hérodote", "Héroïsme", "Hiérarchie", "Histoire", "Historiographie", "Homère", "Hoplite",
  "Iliade", "Impérialisme", "Impôt", "Inauguration", "Indépendance", "Influence", "Invasion",
  "Isocrate", "Isthme",
  "Japon", "Jules César", "Jupiter", "Jurisprudence", "Justice",
  "Laconique", "Légion", "Légionnaire", "Législateur", "Légitimité", "Ligue de Délos",
  "Limès", "Lois", "Lois de Solon",
  "Macédoine", "Magistrat", "Magistrature", "Maison", "Marathon", "Mausolée", "Méditerranée",
  "Mégalopole", "Mégapole", "Mercenaire", "Mésopotamie", "Métèque", "Méthode", "Micromégas",
  "Militarisme", "Miltiade", "Mines du Laurion", "Minorité", "Minotaure", "Misthos", "Monarchie",
  "Monastère", "Monothéisme", "Monument", "Mosaïque", "Murs", "Mycènes", "Mythologie",
  "Nation", "Naval", "Navigation", "Néolithique", "Néron", "Nil", "Noblesse", "Nomade",
  "Notables", "Nuance",
  "Octave", "Odeur", "Odyssée", "Oligarchie", "Olympe", "Olympie", "Oracle", "Oraison funèbre",
  "Ostracisme", "Ostracon", "Ottoman",
  "Palais", "Paléolithique", "Panathénées", "Panthéon", "Pape", "Papyrus", "Parchemin",
  "Parlement", "Parthénon", "Patricien", "Patrie", "Pax Romana", "Paysan", "Péloponnèse",
  "Péninsule", "Pensée", "Périclès", "Pharaon", "Phidias", "Philosophe", "Philosophie",
  "Phénicie", "Pirée", "Platon", "Plébéien", "Plèbe", "Pnyx", "Polis", "Politique",
  "Polythéisme", "Pompéi", "Pompée", "Pontife", "Population", "Poseidon", "Pouvoir",
  "Préteur", "Progrès", "Prolétariat", "Prophète", "Prospérité", "Protagoras", "Province",
  "Ptolémée", "Punique", "Pyramide", "Pyrrhus",
  "Questeur", "Quorum",
  "Radical", "Raison", "Recensement", "Régime", "Règlement", "Relief", "Religion",
  "Renaissance", "République", "République romaine", "Révolution", "Rhéteur", "Rhétorique",
  "Richesse", "Rome", "Romain", "Royaume", "Ruines", "Rural",
  "Salamine", "Sanctuaire", "Sapience", "Sarcophage", "Satrapie", "Scipion", "Scribe",
  "Secteur", "Sécurité", "Sénat", "Sénateur", "Sépulture", "Servitude", "Siècle de Périclès",
  "Socrate", "Solder", "Solon", "Sophiste", "Sources", "Souverain", "Souveraineté",
  "Sparte", "Spartiate", "Statue", "Stèle", "Stoïcisme", "Stratège", "Stratégie",
  "Succession", "Suffrage", "Symbole", "Symposion", "Synoecisme",
  "Tactique", "Talent", "Tarquin", "Temple", "Territoire", "Thalassocratie", "Théâtre",
  "Thèbes", "Thémistocle", "Théocratie", "Thermopyles", "Thésée", "Thètes", "Thucydide",
  "Tirage au sort", "Tite-Live", "Tombeau", "Toge", "Tragédie", "Traité", "Transition",
  "Tribune", "Tribun", "Tribut", "Trière", "Triomphe", "Tyrannie", "Tyran",
  "Union", "Universel", "Urbain", "Urbanisation", "Usurpateur",
  "Vandale", "Vassal", "Vatican", "Vecteur", "Vente", "Vénus", "Vercingétorix",
  "Vétéran", "Victoire", "Village", "Ville", "Volonté", "Vote",
  "Xerxès", "Xénophon", "Zélote", "Zeus",

  // Moyen Âge & Époque moderne
  "Abbaye", "Absolu", "Absolutisme", "Adoubement", "Agriculture", "Allégeance", "Armoiries",
  "Artisan", "Aubergiste", "Autel", "Avignon", "Bailli", "Ban", "Baron", "Basileus",
  "Bastille", "Bâtard", "Bénédictin", "Blason", "Bourgeois", "Bourgeoisie", "Bulle pontificale",
  "Capétien", "Capitaine", "Carolingien", "Cathédrale", "Catholique", "Censitaire",
  "Chancelier", "Chanson de geste", "Chapelle", "Charbon", "Charlemagne", "Château",
  "Châtelain", "Chevalerie", "Chrétien", "Chrétienté", "Chronique", "Clergé", "Cloître",
  "Clovis", "Colbert", "Commerce triangulaire", "Commune", "Compagnie", "Comte", "Condamnation",
  "Confrérie", "Corporation", "Corvée", "Couronne", "Croisades", "Curé",
  "Dîme", "Diplomatie", "Doge", "Donjon", "Duc", "Duché", "Dynastie capétienne",
  "Échevin", "Édit de Nantes", "Église", "Enluminure", "Épidémie", "Évêque",
  "Féodal", "Féodalité", "Fief", "Flandre", "Foire", "Fossé", "Foyer",
  "Gabelle", "Garde", "Gentilhomme", "Gothique", "Grande Peste", "Guilde", "Guerre de Cent Ans",
  "Henri IV", "Heures", "Hommage", "Huguenot", "Humanisme",
  "Imprimerie", "Inquisition", "Intendant", "Islam",
  "Jacquerie", "Jeanne d'Arc", "Journée", "Jouvence", "Justice royale",
  "Kahn", "Kermesse",
  "Lancelot", "Lépreux", "Lignage", "Louis XIV", "Luthérien",
  "Magna Carta", "Manoir", "Manufacture", "Marchand", "Médiéval", "Mercantilisme",
  "Mérovingien", "Messager", "Meurtre", "Milice", "Miniature", "Moine", "Molinisme",
  "Monarque", "Montjoie", "Moyen Âge", "Moulin",
  "Nef", "Nobles", "Notaire", "Notre-Dame",
  "Ordre", "Orfèvre", "Ost",
  "Pape d'Avignon", "Paroissien", "Paroisse", "Pasteur", "Pélerin", "Pèlerinage",
  "Peste Noire", "Pont", "Prieuré", "Privilège", "Protestant", "Protestantisme",
  "Quartier", "Querelle",
  "Rançon", "Reconquista", "Réforme", "Régent", "Relique", "Rentes", "Renaissance italienne",
  "Roi", "Roi-Soleil", "Roman", "Romanesque", "Roturier", "Royaume de France",
  "Sacramentel", "Sacre", "Saint-Louis", "Sceau", "Seigneur", "Seigneurie", "Serf",
  "Servage", "Serment", "Souveraineté royale", "Sujet",
  "Taille", "Templier", "Tenure", "Testament", "Tournoi", "Trêve de Dieu",
  "Universités", "Urbain II",
  "Vassalité", "Versailles", "Vignoble", "Ville franche",

  // Révolution, XIXe, XXe siècle & Monde contemporain
  "Actionnaire", "Administration", "Allemand", "Alliance", "Alsace-Lorraine", "Américain",
  "Anarchisme", "Armistice", "Assemblée nationale", "Attentat", "Aviation",
  "Belligérant", "Bismarck", "Blocus", "Bolchevik", "Bombardement", "Bourse",
  "Capitalisme", "Censure militaire", "Chambre des députés", "Charbonnage", "Chauffeur",
  "Chemin de fer", "Cité ouvrière", "Clemenceau", "Collectivisation", "Colonialisme",
  "Combat", "Communisme", "Commune de Paris", "Concentration", "Conférence", "Conflit",
  "Conscription", "Constitution", "Convention", "Cordon sanitaire", "Crise de 1929",
  "Débarquement", "Décolonisation", "Déclaration des droits", "Défaite", "Déportation",
  "Dépression", "Désarmement", "Destruction", "Détente", "Dictature militaire",
  "Directoire", "Dissuasion", "Doctrine", "Douma",
  "Économie de guerre", "Embranchement", "Emigration", "Empire colonial", "Engagé",
  "Entente", "Espionnage", "États-Unis", "Exode", "Exposition universelle",
  "Fascisme", "Fédération", "Feu", "Filière", "Front populaire", "Front ouest",
  "Gare", "Gaz", "Génocide", "Goulag", "Grande Dépression", "Guerre froide",
  "Guerre totale", "Guerre de tranchées", "Guerre d'anéantissement", "Guerre d'Espagne",
  "Haut fourneau", "Hitler", "Holocauste", "Hopital",
  "Idéologie", "Immigré", "Imperial", "Industrie", "Industrialisation", "Inflation",
  "Insurrection", "Internationalisme", "Intervention",
  "Jaurès", "Jeunesse hitlérienne", "Judaïsme",
  "Komintern", "Kollaborateur",
  "Lénine", "Libéralisme", "Libération", "Ligne Maginot", "Loi de séparation",
  "Machine à vapeur", "Mandat", "Manifestation", "Marxisme", "Massacre", "Métallurgie",
  "Mineur", "Mobilisation", "Modernisation", "Mouvement ouvrier", "Mussolini",
  "Nationalisme", "Nationalisation", "Nazi", "Nazisme", "Neutralité", "Nucléaire",
  "Occupation", "Obus", "Offensive", "ONU", "Ouvrier", "Ouvrière",
  "Pacte", "Parti", "Parti communiste", "Patriote", "Pétain", "Poilu", "Pologne",
  "Propagande", "Protectionnisme", "Puissance",
  "Quatorze points", "Question d'Orient",
  "Rationnement", "Razzia", "Reconstruction", "Réfugié", "Reich", "République de Weimar",
  "Résistance", "Révolution industrielle", "Révolution russe", "Roosevelt", "Ruhr",
  "Sabotage", "Section", "Semaine sanglante", "Shoah", "Socialisme", "Société des Nations",
  "Soviétique", "Staline", "Stalingrad", "Suffrage universel", "Syndicat", "Syndicalisme",
  "Tchécoslovaquie", "Terreur", "Totalitarisme", "Tranchée", "Traité de Versailles",
  "Triple-Alliance", "Triple-Entente", "Tsar",
  "Union soviétique", "Usine", "Utopie",
  "Verdun", "Vichy", "Victoire alliée", "Voleur",
  "Wall Street", "Wilson",

  // Géographie (Espaces, dynamiques, mondialisation, développement)
  "Accessibilité", "Agriculture commerciale", "Agroalimentaire", "Alizé", "Aménagement",
  "Archipel", "Armature urbaine", "Arrière-pays", "Artificialisation", "Attractivité",
  "Autonomie", "Axe de communication",
  "Bassin", "Bassin de vie", "Bassin versant", "Biodiversité", "Biocarburant",
  "Capitale", "Cartographie", "Centre", "Centre-ville", "Changement climatique",
  "Climat", "Concentration spatiale", "Conflit d'usage", "Conurbation", "Croissance",
  "Décentralisation", "Déchet", "Déforestation", "Densité", "Désert", "Désenclavement",
  "Développement durable", "Disparité", "Distance", "Distribution", "Division internationale",
  "Échange", "Échelle", "Écologie", "Économie", "Écosystème", "Écoumène", "Éloignement",
  "Énergie", "Énergie renouvelable", "Ensoleillement", "Environnement", "Érosion",
  "Espace", "Espace rural", "Espace urbain", "Espace productif", "Exportation",
  "Façade maritime", "Fardeau", "Flux", "Flux financier", "Flux migratoire", "Foyer de peuplement",
  "Fragmentation", "Frontière",
  "Gentrification", "Gentrifieur", "Ghetto", "Gisement", "Globalisation", "Gouvernance",
  "Habitat", "Héliotropisme", "Hémisphère", "Hinterland", "Hub", "Hydrocarbure",
  "IDH", "Île", "Immigration", "Impact", "Importation", "Industrie de pointe", "Inondation",
  "Insolation", "Interface", "Intermodalité", "Irrigation",
  "Littoral", "Littoralisation", "Logistique",
  "Mégalopole européenne", "Métropole", "Métropolisation", "Migration", "Milieu",
  "Mobiité", "Mondialisation", "Montagne", "Multinationale",
  "Nappes", "Nœud", "Nord", "Nourricier",
  "Oasis", "Océan", "Organisation",
  "Périphérie", "Périurbanisation", "Plaque", "Plateforme multimodale", "Plateau",
  "Pôle", "Pôle de compétitivité", "Pollution", "Polynucléaire", "Port",
  "Précipitation", "Production", "Proximité",
  "Quartier d'affaires", "Quaternaire",
  "Réseau", "Ressource", "Ressource halieutique", "Risque", "Risque naturel",
  "Sédimentation", "Ségrégation", "Services", "Seuil", "SIG", "Site", "Situation",
  "Sous-développement", "Spécialisation", "Statistique", "Sud",
  "Technopôle", "Territoire", "Territoire ultramarin", "Tertiaire", "Tourisme",
  "Transfrontalier", "Transition démographique", "Transition énergétique", "Transport",
  "Triade", "Tsunami",
  "Ubérisation", "Urbanisation mondiale", "Usufruit",
  "Vallée", "Végétation", "Ville mondiale", "Vulnérabilité",
  "Zone franche", "Zone industrielle", "ZEE",

  // EMC, Citoyenneté & Institutions
  "Abstention", "Adhésion", "Amendement", "Appartenance", "Arbitrage", "Association",
  "Bien commun", "Bulletin", "Burqa",
  "Campagne électorale", "Charte de laïcité", "Citoyen engagé", "Civisme", "Civilité",
  "Cohésion", "Conseil constitutionnel", "Conseil d'État", "Constitution de 1958",
  "Cour européenne", "Croyance",
  "Débat", "Déclaration universelle", "Démocratie participative", "Démocratie représentative",
  "Devoir", "Discrimination", "Droit d'asile", "Droit de grève", "Droit de vote",
  "Égalité hommes-femmes", "Élection", "Électeur", "Éligibilité", "Emc", "Engagement",
  "État de droit", "Européen",
  "Fraternité",
  "Gouvernement",
  "Hémicycle",
  "Identité", "Impartialité", "Institution", "Intérêt général",
  "Jugement", "Juridiction", "Justice des mineurs",
  "Laïc", "Laïcité", "Légal", "Législatif", "Légalité", "Liberté", "Liberté d'expression",
  "Liberté de culte", "Liberté de réunion", "Loi organique",
  "Maire", "Mandat électoral", "Militant", "Ministre",
  "Nationalité", "Neutralité de l'État", "Norme",
  "Opposition",
  "Parlementaire", "Participation", "Pluralisme", "Pouvoir exécutif", "Pouvoir judiciaire",
  "Pouvoir législatif", "Premier ministre", "Président de la République", "Présomption d'innocence",
  "Principe",
  "Rapporteur", "Référendum", "Règlement intérieur", "République indivisible", "Responsabilité",
  "Scrutin", "Scrutin majoritaire", "Scrutin proportionnel", "Séparation des pouvoirs",
  "Solidarité", "Souveraineté nationale", "Suffrage censitaire", "Suffrage direct",
  "Tribunal",
  "Valeur", "Valeurs républicaines", "Voter"
];
